name: Event Notifier

on:
  issues:
    types: [opened, reopened]

permissions:
  issues: read

jobs:
  notify:
    name: "Telegram notification"
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Send Telegram notification for new issue
        uses: reagento/relator@8f09fca8c4214c892dd1580da3ae10f10e9ab66b # v1.5.1
        with:
          tg-bot-token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          tg-chat-id: "@bebraqwez"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          custom-labels: 'test-issue,zed'
